# 作業目標  
1.[簡答題]請問下列兩種將Array轉換成List的方式有何不同?  
    
    print('list(a): ', list(a))  
    print('tolist(): ', a.tolist())
    
2.請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type)  

    a = np.random.randint(10, size=6) 
    b = np.random.randint(10, size=(3,4)) 
    c = np.random.randint(10, size=(2,3,2)) 

3.如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。

## 作業

### 1.[簡答題]請問下列兩種將Array轉換成List的方式有何不同?  
    print('list(a): ', list(a))  
    print('tolist(): ', a.tolist())

In [6]:
import numpy as np

a = np.random.randint(10, size=6)

print('list(a): ', list(a))
print('a.tolist(): ', a.tolist())

b = np.random.randint(10, size=6).reshape(3,2)

print('list(b): ', list(b))
print('b.tolist(): ', b.tolist())



list(a):  [8, 0, 4, 0, 7, 0]
a.tolist():  [8, 0, 4, 0, 7, 0]
list(b):  [array([2, 6]), array([7, 2]), array([6, 5])]
b.tolist():  [[2, 6], [7, 2], [6, 5]]


>* list()只能將第一層的元素轉換成陣列  
* tolist()能將多層的型態完全轉換

### 2.請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果?（屬性：ndim、shape、size、dtype、itemsize、length、type）

    a = np.random.randint(10, size=6)  
    b = np.random.randint(10, size=(3,4))   
    c = np.random.randint(10, size=(2,3,2))  


In [7]:
import numpy as np

a = np.random.randint(10, size=6)

print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))
print(type(a))

[8 5 5 1 6 5]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


In [11]:
import numpy as np

c = np.random.randint(10, size=(2,3,2)) 

print(c)                
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(len(c))
print(type(c))

[[[2 9]
  [5 6]
  [5 4]]

 [[2 4]
  [6 0]
  [1 8]]]
3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


In [8]:
import numpy as np

b = np.random.randint(10, size=(3,4))

print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(len(b))
print(type(b))

[[7 3 8 3]
 [6 1 6 5]
 [1 4 6 9]]
2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>


>* ndarray.ndim:陣列的維度
* ndarray.shape:每個維度的大小
* ndarray.size:陣列的元素個數
* ndarray.dtype:陣列的元素型態
* ndarray.itemsize:每個元素佔用的空間
* len():返回對象的長度或項目個數
* type():返回對象的類型

### 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。

In [12]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))

[5, 2, 4, 0, 7, 0]
[5, 2, 4, 0, 7, 0]


In [13]:
b = np.random.randint(10, size=(3,4))

print(b.tolist())
print(list(b))

[[3, 9, 3, 2], [5, 3, 0, 3], [6, 5, 1, 4]]
[array([3, 9, 3, 2]), array([5, 3, 0, 3]), array([6, 5, 1, 4])]


In [14]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))

[[[5, 5], [5, 7], [7, 3]], [[5, 8], [4, 4], [8, 1]]]
[array([[5, 5],
       [5, 7],
       [7, 3]]), array([[5, 8],
       [4, 4],
       [8, 1]])]


In [15]:
def tolist(iterable):
    
    if type(iterable) != np.ndarray:
        return iterable
    return [tolist(obj) for obj in iterable]
    
print(tolist(a))
print(tolist(b))
print(tolist(c))

[5, 2, 4, 0, 7, 0]
[[3, 9, 3, 2], [5, 3, 0, 3], [6, 5, 1, 4]]
[[[5, 5], [5, 7], [7, 3]], [[5, 8], [4, 4], [8, 1]]]
